services:
  keydb:
    image: beats-admin
    container_name: beats-admin
    ports:
      - "127.0.0.1:9000:9000"  # Accessible only from the host
    env_file:
      - ./.env
    networks:
      - ann-network
    restart: always

    