version: "3.8"

services:
  keydb:
    image: kaetaro13/beats-admin
    container_name: beats-admin
    ports:
      - "127.0.0.1:9000:9000"  # Accessible only from the host
    env_file:
      - ./.env
    networks:
      - existing-network  # Attach to the existing network
    restart: always

networks:
  existing-network:
    external: true  # Use an external network
    name: gmr-beats-server-bun-ts_ann-network  # Match the existing network name
